"use client";

import { FormEvent, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { evidenceStyle, oxidativePathway, PathwayNode } from "../lib/pathway";
import { fetchLatestPM25, LivePM25 } from "../lib/airQuality";

const DISCLAIMER = "This platform is an educational and research-oriented computational model. It does not diagnose disease, estimate an individual's cancer risk, or predict whether a specific mutation will occur. Biological pathways shown are based on published evidence and simplified computational representations.";

function Badge({ level }: { level: PathwayNode["evidence_level"] }) {
  const text = level === "established" ? "Established" : level === "model-based" ? "Model-based" : "Exploratory";
  return <span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${evidenceStyle[level]}`}>{text}</span>;
}

function MutationExplorer() {
  const [sequence, setSequence] = useState("ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG");
  const [position, setPosition] = useState(4);
  const [alternate, setAlternate] = useState("T");
  const result = useMemo(() => {
    const source = sequence.toUpperCase().replace(/\s/g, ""); const alt = alternate.toUpperCase();
    if (!/^[ACGT]+$/.test(source) || !/^[ACGT]$/.test(alt) || position < 1 || position > source.length) return null;
    const ref = source[position - 1]; const mutated = source.slice(0, position - 1) + alt + source.slice(position);
    const start = Math.floor((position - 1) / 3) * 3; const codon = source.slice(start,start+3); const changed = mutated.slice(start,start+3);
    if (codon.length < 3) return null;
    const table: Record<string,string> = { TTT:"F",TTC:"F",TTA:"L",TTG:"L",CTT:"L",CTC:"L",CTA:"L",CTG:"L",ATT:"I",ATC:"I",ATA:"I",ATG:"M",GTT:"V",GTC:"V",GTA:"V",GTG:"V",TCT:"S",TCC:"S",TCA:"S",TCG:"S",CCT:"P",CCC:"P",CCA:"P",CCG:"P",ACT:"T",ACC:"T",ACA:"T",ACG:"T",GCT:"A",GCC:"A",GCA:"A",GCG:"A",TAT:"Y",TAC:"Y",TAA:"*",TAG:"*",CAT:"H",CAC:"H",CAA:"Q",CAG:"Q",AAT:"N",AAC:"N",AAA:"K",AAG:"K",GAT:"D",GAC:"D",GAA:"E",GAG:"E",TGT:"C",TGC:"C",TGA:"*",TGG:"W",CGT:"R",CGC:"R",CGA:"R",CGG:"R",AGT:"S",AGC:"S",AGA:"R",AGG:"R",GGT:"G",GGC:"G",GGA:"G",GGG:"G" };
    const aa = table[codon], changedAa = table[changed]; const classification = ref === alt ? "no change" : aa === changedAa ? "synonymous" : changedAa === "*" ? "nonsense" : "missense";
    return { ref, codon, changed, aa, changedAa, classification, codonNumber: start / 3 + 1 };
  }, [sequence, position, alternate]);
  return <section id="mutation" className="mt-20 grid gap-8 lg:grid-cols-[1.05fr_.95fr]">
    <div><p className="eyebrow">Hypothetical variant annotation</p><h2 className="mt-2 text-3xl font-semibold">Mutation Explorer</h2><p className="mt-3 max-w-xl text-slate-300">Inspect a small coding-sequence substitution with deterministic codon translation. This does not establish a real-world clinical variant or its health effect.</p></div>
    <div className="glass rounded-2xl p-5"><div className="grid gap-3 sm:grid-cols-[1fr_92px_92px]"><div><label>DNA sequence</label><input aria-label="DNA sequence" value={sequence} onChange={e=>setSequence(e.target.value)} /></div><div><label>Position</label><input aria-label="position" type="number" value={position} onChange={e=>setPosition(Number(e.target.value))} /></div><div><label>Alternate</label><input aria-label="alternate nucleotide" maxLength={1} value={alternate} onChange={e=>setAlternate(e.target.value)} /></div></div>
    {result ? <div className="mt-5 grid grid-cols-3 gap-2 text-center"><Metric label="DNA" value={`${result.ref} → ${alternate.toUpperCase()}`} /><Metric label={`Codon ${result.codonNumber}`} value={`${result.codon} → ${result.changed}`} /><Metric label="Protein" value={`${result.aa} → ${result.changedAa}`} /><div className="col-span-3 rounded-lg border border-cyan/25 bg-cyan/5 p-3 text-sm"><b className="text-cyan">{result.classification}</b> substitution · consequence depends on the actual gene, transcript, and biological context.</div></div> : <p className="mt-4 text-sm text-sun">Enter a valid A/C/G/T sequence and a position within a complete codon.</p>}</div>
  </section>;
}
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-lg bg-black/20 p-3"><p className="text-[10px] uppercase tracking-widest text-slate-400">{label}</p><p className="mt-1 font-mono text-sm text-lime">{value}</p></div>; }

export default function Home() {
  const [started, setStarted] = useState(false); const [pm25, setPm25] = useState(150); const [pm10, setPm10] = useState(0); const [no2, setNo2] = useState(0); const [ozone, setOzone] = useState(0); const [hours, setHours] = useState(8); const [setting, setSetting] = useState("outdoor"); const [active, setActive] = useState<PathwayNode>(oxidativePathway[0]); const [liveReading, setLiveReading] = useState<LivePM25 | null>(null); const [liveLoading, setLiveLoading] = useState(false); const [liveError, setLiveError] = useState<string | null>(null);
  const exposureIndex = pm25 * hours;
  function trace(e: FormEvent) { e.preventDefault(); setStarted(true); setActive(oxidativePathway[0]); setTimeout(()=>document.getElementById("trace")?.scrollIntoView({behavior:"smooth", block:"center"}), 50); }
  async function useLatestNEA() { setLiveLoading(true); setLiveError(null); try { const reading = await fetchLatestPM25(); if (reading.pm25_ug_m3 === null) throw new Error("The selected NEA region has no current PM2.5 reading."); setPm25(reading.pm25_ug_m3); setLiveReading(reading); } catch (error) { setLiveError(error instanceof Error ? error.message : "Unable to load the latest NEA PM2.5 reading."); } finally { setLiveLoading(false); } }
  return <main className="shell"><nav className="flex items-center justify-between"><div className="font-semibold tracking-[.22em] text-cyan">AIR2DNA</div><a className="text-sm text-slate-300 hover:text-cyan" href="#science">SCIENCE & LIMITS</a></nav>
  <section className="grid min-h-[530px] items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">Environmental molecular biology · UnivaBio 2026</p><h1 className="mt-4 text-5xl font-semibold tracking-tight sm:text-7xl">From air,<br/><span className="text-cyan">to biology.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">AIR2DNA makes invisible molecular mechanisms explorable—tracing evidence-supported pathways from pollution exposure to potential DNA and protein consequences.</p><div className="mt-8 flex gap-3"><button className="button button-primary" onClick={()=>document.getElementById("scenario")?.scrollIntoView({behavior:"smooth"})}>Trace the Path</button><a className="button button-quiet" href="#science">Explore the Science</a></div></div>
  <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="glass relative overflow-hidden rounded-3xl p-8"><div className="absolute inset-0 opacity-30 [background:radial-gradient(circle_at_center,#65e5e055,transparent_45%)]"/><p className="relative eyebrow">Mechanistic lens</p><div className="relative mt-9 flex items-center justify-between text-center"><Orbit icon="◌" label="AIR"/><div className="line"/><Orbit icon="◉" label="CELL"/><div className="line"/><Orbit icon="⌁" label="DNA"/><div className="line"/><Orbit icon="◇" label="PROTEIN"/></div><p className="relative mt-10 text-sm leading-6 text-slate-300">A chain of evidence, uncertainty, and hypothesis—not a personal health forecast.</p></motion.div></section>
  <section id="scenario" className="glass rounded-3xl p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">01 · Configure an exposure</p><h2 className="mt-2 text-2xl font-semibold">Singapore haze demo</h2></div><Badge level="model-based" /></div><div className="mt-5 flex flex-wrap items-center gap-3 rounded-xl border border-cyan/20 bg-cyan/5 p-4"><div className="flex-1"><p className="text-sm font-semibold text-cyan">Live PM2.5 from Singapore NEA</p><p className="mt-1 text-xs text-slate-400">Loads the latest central-region ambient reading through AIR2DNA&apos;s server-side proxy. The default 150 μg/m³ haze value remains a fixed demonstration scenario.</p></div><button type="button" className="button button-quiet text-sm" onClick={useLatestNEA} disabled={liveLoading}>{liveLoading ? "Loading…" : "Use latest NEA reading"}</button></div>{liveReading && <p className="mt-3 text-xs text-lime">Live source: {liveReading.source} · central {liveReading.pm25_ug_m3} {liveReading.unit} · observed {new Date(liveReading.timestamp).toLocaleString()} · {liveReading.freshness_note}</p>}{liveError && <p role="alert" className="mt-3 text-xs text-sun">Live data unavailable: {liveError} The demonstration scenario is still available.</p>}<form onSubmit={trace} className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Field label="Location"><select defaultValue="Singapore"><option>Singapore</option></select></Field><Field label="Scenario"><select defaultValue="Haze episode"><option>Haze episode</option><option>Custom scenario</option></select></Field><Field label="PM2.5 (μg/m³)"><input type="number" min="0" value={pm25} onChange={e=>{setPm25(Number(e.target.value)); setLiveReading(null);}}/></Field><Field label="PM10 optional (μg/m³)"><input type="number" min="0" value={pm10} onChange={e=>setPm10(Number(e.target.value))}/></Field><Field label="Duration (hours)"><input type="number" min="1" value={hours} onChange={e=>setHours(Number(e.target.value))}/></Field><Field label="NO₂ optional (μg/m³)"><input type="number" min="0" value={no2} onChange={e=>setNo2(Number(e.target.value))}/></Field><Field label="Ozone optional (μg/m³)"><input type="number" min="0" value={ozone} onChange={e=>setOzone(Number(e.target.value))}/></Field><Field label="Setting"><select value={setting} onChange={e=>setSetting(e.target.value)}><option value="outdoor">Outdoor</option><option value="indoor">Indoor</option></select></Field><div className="sm:col-span-2 lg:col-span-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4"><p className="text-sm text-slate-300">Concentration × time descriptor: <b className="font-mono text-lime">{exposureIndex.toLocaleString()} μg·h/m³</b> <span className="text-slate-500">— PM2.5 is the primary MVP signal; optional pollutants are captured but not modeled.</span></p><button className="button button-primary" type="submit">TRACE →</button></div></form></section>
  <AnimatePresence>{started && <motion.section id="trace" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mt-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">02 · Trace the path</p><h2 className="mt-2 text-3xl font-semibold">A modeled oxidative-damage pathway</h2></div><button className="button button-quiet text-sm" onClick={()=>{setStarted(false); setActive(oxidativePathway[0]);}}>Restart trace</button></div><p className="mt-3 max-w-3xl text-slate-300">For this {pm25} μg/m³, {hours}-hour {setting} scenario, nodes describe an evidence-supported chain of possible biological mechanisms. Click a node to inspect its scope.</p><div className="mt-7 overflow-x-auto pb-3"><div className="flex min-w-[1120px] items-center gap-2">{oxidativePathway.map((node,index)=><div className="flex items-center gap-2" key={node.id}><motion.button initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:index*.1}} onClick={()=>setActive(node)} className={`node text-left ${active.id===node.id?"node-active":""}`}><Badge level={node.evidence_level}/><p className="mt-3 text-sm font-semibold">{node.title}</p></motion.button>{index<oxidativePathway.length-1 && <div className="line w-6 flex-none"/>}</div>)}</div></div><EvidenceDrawer node={active}/></motion.section>}</AnimatePresence>
  <MutationExplorer />
  <section id="science" className="mt-20 border-t border-white/10 pt-8"><p className="eyebrow">Scientific boundary</p><h2 className="mt-2 text-2xl font-semibold">Evidence first. Certainty never invented.</h2><p className="mt-3 max-w-4xl leading-7 text-slate-300">{DISCLAIMER}</p><div className="mt-6 grid gap-4 md:grid-cols-3"><Legend color="lime" title="Established" text="Strongly supported biological mechanisms."/><Legend color="sun" title="Supported / model-based" text="Context-dependent connections represented transparently."/><Legend color="slate-400" title="Exploratory" text="Hypothetical downstream consequence, never a prediction."/></div></section><footer className="mt-16 text-xs text-slate-500">AIR2DNA · UnivaBio 2026 · Educational computational model</footer></main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}) { return <div><label>{label}</label>{children}</div>; }
function Orbit({icon,label}:{icon:string;label:string}) { return <div><div className="grid h-14 w-14 place-items-center rounded-full border border-cyan/50 bg-cyan/10 text-3xl text-cyan">{icon}</div><p className="mt-2 text-[10px] font-bold tracking-widest text-slate-300">{label}</p></div>; }
function Legend({color,title,text}:{color:string;title:string;text:string}) { const dot = color === "lime" ? "bg-lime" : color === "sun" ? "bg-sun" : "bg-slate-400"; return <div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><span className={`inline-block h-2 w-2 rounded-full ${dot}`}/><p className="mt-3 font-semibold">{title}</p><p className="mt-1 text-sm text-slate-400">{text}</p></div>; }
function EvidenceDrawer({node}:{node:PathwayNode}) { return <div className="glass mt-6 grid gap-5 rounded-2xl p-6 lg:grid-cols-[1.15fr_.85fr]"><div><div className="flex items-center gap-3"><Badge level={node.evidence_level}/><span className="text-xs text-slate-500">EVIDENCE DETAIL</span></div><h3 className="mt-3 text-2xl font-semibold">{node.title}</h3><p className="mt-3 leading-7 text-slate-200">{node.description}</p></div><div className="rounded-xl border border-sun/25 bg-sun/5 p-4"><p className="text-xs font-bold uppercase tracking-widest text-sun">Uncertainty & limitations</p><p className="mt-2 text-sm leading-6 text-slate-300">{node.uncertainty}</p><div className="mt-4 border-t border-white/10 pt-3">{node.references.length ? node.references.map(ref=><a key={ref.url} target="_blank" rel="noreferrer" href={ref.url} className="block text-sm text-cyan hover:underline">{ref.label}<span className="mt-1 block text-xs text-slate-400 no-underline">{ref.summary}</span></a>) : <p className="text-sm text-slate-400">No standalone reference: this node is intentionally presented as exploratory.</p>}</div></div></div>; }
