export type EvidenceLevel = "established" | "model-based" | "hypothetical";
export type Reference = { label: string; url: string; summary: string };
export type PathwayNode = { id:string; title:string; description:string; evidence_level:EvidenceLevel; uncertainty:string; references:Reference[]; next_nodes:string[] };
export const oxidativePathway: PathwayNode[] = [
 {id:"pm25",title:"PM2.5 exposure",description:"Fine particulate matter can carry reactive constituents and is associated with oxidative stress pathways.",evidence_level:"established",uncertainty:"Particle chemistry and the deposited dose vary across sources and people.",references:[{label:"WHO Global Air Quality Guidelines (2021)",url:"https://www.who.int/publications/i/item/9789240034228",summary:"Authoritative evidence review for particulate matter."}],next_nodes:["oxidative-stress"]},
 {id:"oxidative-stress",title:"Oxidative stress",description:"Particle-associated components can contribute to an imbalance between oxidants and antioxidant defenses.",evidence_level:"established",uncertainty:"This mechanism does not measure an individual response.",references:[{label:"Valavanidis et al., Part Fibre Toxicol. (2008)",url:"https://pubmed.ncbi.nlm.nih.gov/18325195/",summary:"Review of particulate matter, oxidative stress, and DNA damage."}],next_nodes:["ros"]},
 {id:"ros",title:"Reactive oxygen species",description:"Reactive oxygen species can modify DNA bases when cellular defenses and repair do not fully compensate.",evidence_level:"established",uncertainty:"Effects are transient and cell-context dependent.",references:[{label:"Cooke et al., FASEB J. (2003)",url:"https://pubmed.ncbi.nlm.nih.gov/12709404/",summary:"Oxidative DNA damage mechanisms and biomarkers."}],next_nodes:["8-oxo-dg"]},
 {id:"8-oxo-dg",title:"8-oxo-dG lesion",description:"8-oxo-7,8-dihydroguanine is a widely used oxidative-DNA-damage biomarker and can mispair during replication.",evidence_level:"established",uncertainty:"This diagram cannot infer lesion abundance in a person or tissue.",references:[{label:"Nakabeppu, Mutagenesis (2014)",url:"https://pubmed.ncbi.nlm.nih.gov/24368813/",summary:"Formation, mutagenesis, and repair of 8-oxoguanine."}],next_nodes:["repair"]},
 {id:"repair",title:"Base-excision repair",description:"Repair enzymes including OGG1 can recognize and remove oxidized bases.",evidence_level:"established",uncertainty:"Repair capacity varies by cell state and context.",references:[{label:"David et al., Nat Rev Mol Cell Biol. (2007)",url:"https://pubmed.ncbi.nlm.nih.gov/18007677/",summary:"Base-excision repair and genome stability."}],next_nodes:["mutation"]},
 {id:"mutation",title:"Potential error",description:"If a lesion persists into replication or repair is imperfect, a sequence change is a possible downstream consequence.",evidence_level:"model-based",uncertainty:"Conditional modeled consequence—not a predicted mutation.",references:[{label:"Nakabeppu, Mutagenesis (2014)",url:"https://pubmed.ncbi.nlm.nih.gov/24368813/",summary:"Mutagenic potential of oxidized guanine."}],next_nodes:["protein"]},
 {id:"protein",title:"Protein consequence",description:"A coding sequence change may be synonymous, alter an amino acid, or truncate a protein depending on its context.",evidence_level:"hypothetical",uncertainty:"A specific validated variant and transcript are required to determine a real consequence.",references:[],next_nodes:[]}
];
export const evidenceStyle: Record<EvidenceLevel,string> = { established:"bg-lime/15 text-lime border-lime/40", "model-based":"bg-sun/15 text-sun border-sun/40", hypothetical:"bg-slate-400/15 text-slate-300 border-slate-400/40" };
